blank_issues_enabled: true
contact_links:
  - name: Project Discussions
    url: https://github.com/batt1984rodrigo-del/tcria/discussions
    about: Ask questions, share ideas, or start a discussion here.
