name: Deploy to Staging

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_pr_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "Iniciando deploy para staging."
          # Adicione comandos de deploy aqui
          echo "Deploy para staging concluído."